export const GOOGLE_SIGNIN_REQUEST = "GOOGLE_SIGNIN_REQUEST";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAIL = "GOOGLE_SIGNIN_FAIL";

export const CUSTOM_SIGNUP_REQUEST = "CUSTOM_SIGNUP_REQUEST";
export const CUSTOM_SIGNUP_SUCCESS = "CUSTOM_SIGNUP_SUCCESS";
export const CUSTOM_SIGNUP_FAIL = "CUSTOM_SIGNUP_FAIL";

export const CUSTOM_SIGNIN_REQUEST = "CUSTOM_SIGNIN_REQUEST";
export const CUSTOM_SIGNIN_SUCCESS = "CUSTOM_SIGNIN_SUCCESS";
export const CUSTOM_SIGNIN_FAIL = "CUSTOM_SIGNIN_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const EMAIL_ACTIVATE_REQUEST = "EMAIL_ACTIVATE_REQUEST";
export const EMAIL_ACTIVATE_SUCCESS = "EMAIL_ACTIVATE_SUCCESS";
export const EMAIL_ACTIVATE_FAIL = "EMAIL_ACTIVATE_FAIL";

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
