export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";

export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_FAIL = "IMAGE_DELETE_FAIL";

export const IMAGE_GET_REQUEST = "IMAGE_GET_REQUEST";
export const IMAGE_GET_SUCCESS = "IMAGE_GET_SUCCESS";
export const IMAGE_GET_FAIL = "IMAGE_GET_FAIL";

export const FROALA_IMAGE_GET_REQUEST = "FROALA_IMAGE_GET_REQUEST";
export const FROALA_IMAGE_GET_SUCCESS = "FROALA_IMAGE_GET_SUCCESS";
export const FROALA_IMAGE_GET_FAIL = "FROALA_IMAGE_GET_FAIL";

export const FROALA_IMAGE_UPLOAD_REQUEST = "FROALA_IMAGE_UPLOAD_REQUEST";
export const FROALA_IMAGE_UPLOAD_SUCCESS = "FROALA_IMAGE_UPLOAD_SUCCESS";
export const FROALA_IMAGE_UPLOAD_FAIL = "FROALA_IMAGE_UPLOAD_FAIL";

export const FROALA_IMAGE_DELETE_REQUEST = "FROALA_IMAGE_DELETE_REQUEST";
export const FROALA_IMAGE_DELETE_SUCCESS = "FROALA_IMAGE_DELETE_SUCCESS";
export const FROALA_IMAGE_DELETE_FAIL = "FROALA_IMAGE_DELETE_FAIL";
