export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";
export const CLEAR_POST_SUCCESS = "CLEAR_POST_SUCCESS";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const CLEAR_POSTS = "CLEAR_POSTS";

export const GET_RECOMENDED_POSTS_REQUEST = "GET_RECOMENDED_POSTS_REQUEST";
export const GET_RECOMENDED_POSTS_SUCCESS = "GET_RECOMENDED_POSTS_SUCCESS";
export const GET_RECOMENDED_POSTS_FAIL = "GET_RECOMENDED_POSTS_FAIL";

export const GET_POSTS_BY_SEARCH_REQUEST = "GET_POSTS_BY_SEARCH_REQUEST";
export const GET_POSTS_BY_SEARCH_SUCCESS = "GET_POSTS_BY_SEARCH_SUCCESS";
export const GET_POSTS_BY_SEARCH_FAIL = "GET_POSTS_BY_SEARCH_FAIL";

export const GET_POSTS_BY_CATEGORY_REQUEST = "GET_POSTS_BY_CATEGORY_REQUEST";
export const GET_POSTS_BY_CATEGORY_SUCCESS = "GET_POSTS_BY_CATEGORY_SUCCESS";
export const GET_POSTS_BY_CATEGORY_FAIL = "GET_POSTS_BY_CATEGORY_FAIL";

export const GET_POSTS_BY_CATEGORY_FOOTER_REQUEST =
  "GET_POSTS_BY_CATEGORY_FOOTER_REQUEST";
export const GET_POSTS_BY_CATEGORY_FOOTER_SUCCESS =
  "GET_POSTS_BY_CATEGORY_FOOTER_SUCCESS";
export const GET_POSTS_BY_CATEGORY_FOOTER_FAIL =
  "GET_POSTS_BY_CATEGORY_FOOTER_FAIL";

export const GET_IFINITE_POSTS_REQUEST = "GET_IFINITE_POSTS_REQUEST";
export const GET_IFINITE_POSTS_SUCCESS = "GET_IFINITE_POSTS_SUCCESS";
export const GET_IFINITE_POSTS_CATEGORY_SUCCESS =
  "GET_IFINITE_POSTS_CATEGORY_SUCCESS";
export const GET_IFINITE_POSTS_FAIL = "GET_IFINITE_POSTS_FAIL";
export const CLEAR_IFINITE_POSTS = "CLEAR_IFINITE_POSTS";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAIL = "GET_USER_POSTS_FAIL";

export const GET_TOP_CATEGORIES_POSTS_REQUEST =
  "GET_TOP_CATEGORIES_POSTS_REQUEST";
export const GET_TOP_CATEGORIES_POSTS_SUCCESS =
  "GET_TOP_CATEGORIES_POSTS_SUCCESS";
export const GET_TOP_CATEGORIES_POSTS_FAIL = "GET_USER_POSTS_FAIL";

export const GET_CATEGORY_POSTS_REQUEST = "GET_CATEGORY_POSTS_REQUEST";
export const GET_CATEGORY_POSTS_SUCCESS = "GET_CATEGORY_POSTS_SUCCESS";
export const GET_CATEGORY_POSTS_FAIL = "GET_CATEGORY_POSTS_FAIL";
